<?php

namespace EchangeoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuggestionCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionCategorieRepository extends EntityRepository
{
}
